# Generated by Django 5.2.9 on 2025-12-26 22:00

import apps.bau_mental.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_add_updated_at_to_password_reset_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('color', models.CharField(blank=True, help_text='Cor em hexadecimal (ex: #FF5733)', max_length=7, null=True, verbose_name='Cor')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.workspace', verbose_name='Workspace')),
            ],
            options={
                'verbose_name': 'Caixinha',
                'verbose_name_plural': 'Caixinhas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('audio_file', models.FileField(upload_to=apps.bau_mental.models.audio_upload_path, verbose_name='Arquivo de áudio')),
                ('transcript', models.TextField(blank=True, null=True, verbose_name='Transcrição')),
                ('source_type', models.CharField(choices=[('memo', 'Memo próprio'), ('group_audio', 'Áudio de grupo')], default='memo', max_length=20, verbose_name='Tipo de origem')),
                ('processing_status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=20, verbose_name='Status de processamento')),
                ('ai_confidence', models.FloatField(blank=True, help_text='Confiança da classificação (0-1)', null=True, verbose_name='Confiança da IA')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='Duração (segundos)')),
                ('file_size_bytes', models.IntegerField(blank=True, null=True, verbose_name='Tamanho do arquivo (bytes)')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados extras')),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='bau_mental.box', verbose_name='Caixinha')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.workspace', verbose_name='Workspace')),
            ],
            options={
                'verbose_name': 'Anotação',
                'verbose_name_plural': 'Anotações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='box',
            index=models.Index(fields=['workspace', 'name'], name='supbrainnot_workspa_e64862_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['workspace', 'box', 'created_at'], name='supbrainnot_workspa_a9ae4d_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['workspace', 'processing_status'], name='supbrainnot_workspa_0d054b_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['workspace', 'box', 'processing_status'], name='supbrainnot_workspa_61869d_idx'),
        ),
    ]
