# Generated by Django 5.2.9 on 2025-12-27 18:41
# Modificado para suportar conversão de bigint para UUID em produção

import uuid
from django.db import migrations, models


def clear_existing_data(apps, schema_editor):
    """Limpa dados existentes antes de alterar primary key para UUID.

    Nota: Esta migration limpa todos os dados existentes de Box e Note
    porque não é possível converter primary keys numéricas para UUID
    sem perder referências. Como são dados de teste, isso é aceitável.
    """
    Box = apps.get_model('bau_mental', 'Box')
    Note = apps.get_model('bau_mental', 'Note')

    # Deletar todas as notas primeiro (devido à foreign key)
    Note.objects.all().delete()
    # Deletar todas as caixinhas
    Box.objects.all().delete()


def reverse_clear_data(apps, schema_editor):
    """Reverter limpeza (não suportado - dados foram deletados)."""
    pass


def convert_box_id_to_uuid(apps, schema_editor):
    """Converte o campo id de Box de bigint para UUID.
    
    Se bau_mental_box já existe com UUID (banco novo), não faz nada.
    Só converte se supbrainnote_box existir com bigint (banco antigo).
    """
    db_alias = schema_editor.connection.alias

    with schema_editor.connection.cursor() as cursor:
        # PRIMEIRO: Verificar se bau_mental_box já existe com UUID (banco novo)
        cursor.execute("""
            SELECT c.data_type
            FROM information_schema.columns c
            JOIN information_schema.tables t ON c.table_name = t.table_name
            WHERE c.table_name = 'bau_mental_box'
            AND c.column_name = 'id'
            AND t.table_schema = 'public'
        """)
        result = cursor.fetchone()
        
        if result and result[0] == 'uuid':
            # Tabela já existe com UUID (banco novo), não fazer nada
            return

        # SEGUNDO: Verificar se supbrainnote_box existe (banco antigo)
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 FROM information_schema.tables
                WHERE table_name = 'supbrainnote_box'
                AND table_schema = 'public'
            )
        """)
        old_table_exists = cursor.fetchone()[0]

        if not old_table_exists:
            # Tabela antiga não existe, não fazer nada
            return

        # Verificar tipo do id na tabela antiga
        cursor.execute("""
            SELECT data_type
            FROM information_schema.columns
            WHERE table_name = 'supbrainnote_box'
            AND column_name = 'id'
            AND table_schema = 'public'
        """)
        result = cursor.fetchone()

        if not result or result[0] == 'uuid':
            # Já é UUID ou não existe, não fazer nada
            return

        # Se chegou aqui, precisa converter supbrainnote_box de bigint para UUID
        table_name = 'supbrainnote_box'
        
        # 1. Remover foreign key constraints de todas as tabelas que referenciam supbrainnote_box.id
        # Isso inclui: supbrainnote_note.box_id e core_notification.related_box_id
        
        # Remover FK de note.box_id (se existir e se a tabela note existir)
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 FROM information_schema.tables
                WHERE table_name = 'supbrainnote_note'
                AND table_schema = 'public'
            )
        """)
        note_table_exists = cursor.fetchone()[0]

        if note_table_exists:
            cursor.execute("""
                SELECT constraint_name
                FROM information_schema.table_constraints
                WHERE table_name = 'supbrainnote_note'
                AND constraint_type = 'FOREIGN KEY'
                AND constraint_name LIKE '%box_id%'
            """)
            fk_constraints = cursor.fetchall()

            for constraint in fk_constraints:
                constraint_name = constraint[0]
                cursor.execute(f'ALTER TABLE supbrainnote_note DROP CONSTRAINT IF EXISTS {constraint_name}')
        
        # Remover FK de core_notification.related_box_id (se existir)
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 FROM information_schema.tables
                WHERE table_name = 'core_notification'
            )
        """)
        notification_table_exists = cursor.fetchone()[0]

        if notification_table_exists:
            # Verificar se related_box_id existe
            cursor.execute("""
                SELECT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'core_notification'
                    AND column_name = 'related_box_id'
                )
            """)
            related_box_id_exists = cursor.fetchone()[0]
            
            if related_box_id_exists:
                # Remover foreign key constraint
                cursor.execute("""
                    SELECT constraint_name
                    FROM information_schema.table_constraints
                    WHERE table_name = 'core_notification'
                    AND constraint_type = 'FOREIGN KEY'
                    AND constraint_name LIKE '%related_box_id%'
                """)
                fk_constraints = cursor.fetchall()

                for constraint in fk_constraints:
                    constraint_name = constraint[0]
                    cursor.execute(f'ALTER TABLE core_notification DROP CONSTRAINT IF EXISTS {constraint_name}')
                
                # Converter related_box_id de bigint para uuid
                # Como não há dados (clear_existing_data foi executado), podemos simplesmente dropar e recriar
                cursor.execute("""
                    ALTER TABLE core_notification
                    ADD COLUMN related_box_id_new UUID
                """)
                cursor.execute("ALTER TABLE core_notification DROP COLUMN related_box_id")
                cursor.execute("ALTER TABLE core_notification RENAME COLUMN related_box_id_new TO related_box_id")

        # Se a tabela é bau_mental_box e já é UUID, não fazer nada
        if table_name == 'bau_mental_box':
            return

        # 2. Criar nova coluna UUID temporária
        cursor.execute("""
            ALTER TABLE supbrainnote_box
            ADD COLUMN id_new UUID DEFAULT gen_random_uuid()
        """)

        # 3. Remover a coluna antiga bigint (CASCADE remove dependências automaticamente)
        cursor.execute("ALTER TABLE supbrainnote_box DROP COLUMN id CASCADE")

        # 4. Renomear a nova coluna para id
        cursor.execute("ALTER TABLE supbrainnote_box RENAME COLUMN id_new TO id")

        # 5. Adicionar constraint de primary key
        cursor.execute("ALTER TABLE supbrainnote_box ADD PRIMARY KEY (id)")
        
        # 6. Renomear tabela para bau_mental_box
        cursor.execute("ALTER TABLE supbrainnote_box RENAME TO bau_mental_box")
        
        # 6. Recriar foreign key em core_notification.related_box_id (se existir)
        if notification_table_exists:
            cursor.execute("""
                SELECT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'core_notification'
                    AND column_name = 'related_box_id'
                )
            """)
            related_box_id_exists = cursor.fetchone()[0]
            
            if related_box_id_exists:
                cursor.execute("""
                    ALTER TABLE core_notification
                    ADD CONSTRAINT core_notification_related_box_id_fk
                    FOREIGN KEY (related_box_id)
                    REFERENCES bau_mental_box(id)
                    ON DELETE SET NULL
                """)


def convert_note_box_id_to_uuid(apps, schema_editor):
    """Converte o campo box_id de Note de bigint para UUID.
    
    Se a tabela não existir ou já for UUID, não faz nada (banco novo).
    """
    db_alias = schema_editor.connection.alias

    with schema_editor.connection.cursor() as cursor:
        # Verificar se a tabela existe (pode ser bau_mental_note se banco novo)
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 FROM information_schema.tables
                WHERE table_name IN ('supbrainnote_note', 'bau_mental_note')
                AND table_schema = 'public'
            )
        """)
        table_exists = cursor.fetchone()[0]

        if not table_exists:
            return

        # Verificar qual tabela existe e tipo de box_id
        cursor.execute("""
            SELECT c.table_name, c.data_type
            FROM information_schema.columns c
            JOIN information_schema.tables t ON c.table_name = t.table_name
            WHERE c.table_name IN ('supbrainnote_note', 'bau_mental_note')
            AND c.column_name = 'box_id'
            AND t.table_schema = 'public'
        """)
        result = cursor.fetchone()

        if not result:
            # Coluna não existe, não fazer nada
            return

        table_name, data_type = result

        if data_type == 'uuid':
            # Já está convertido, não fazer nada
            return

        # Se a tabela é bau_mental_note, não fazer nada (já foi criada com UUID)
        if table_name == 'bau_mental_note':
            return

        # Verificar se box.id já é UUID (precisa estar convertido primeiro)
        cursor.execute("""
            SELECT data_type
            FROM information_schema.columns
            WHERE table_name IN ('supbrainnote_box', 'bau_mental_box')
            AND column_name = 'id'
            AND table_schema = 'public'
        """)
        box_id_type = cursor.fetchone()

        if not box_id_type or box_id_type[0] != 'uuid':
            # Box.id ainda não foi convertido, não fazer nada
            return

        # Se a tabela é bau_mental_note e box_id já é UUID, não fazer nada
        if table_name == 'bau_mental_note':
            return

        # Remover foreign key constraint se existir
        cursor.execute(f"""
            SELECT constraint_name
            FROM information_schema.table_constraints
            WHERE table_name = '{table_name}'
            AND constraint_type = 'FOREIGN KEY'
            AND constraint_name LIKE '%box_id%'
        """)
        fk_constraints = cursor.fetchall()

        for constraint in fk_constraints:
            constraint_name = constraint[0]
            cursor.execute(f'ALTER TABLE {table_name} DROP CONSTRAINT IF EXISTS {constraint_name}')

        # Como não há dados (clear_existing_data foi executado antes), podemos simplesmente dropar e recriar
        cursor.execute(f"""
            ALTER TABLE {table_name}
            ADD COLUMN box_id_new UUID
        """)

        # Se houver dados, precisaríamos fazer um JOIN para copiar os valores
        # Mas como clear_existing_data foi executado, não há dados, então podemos simplesmente dropar
        cursor.execute(f"ALTER TABLE {table_name} DROP COLUMN box_id")
        cursor.execute(f"ALTER TABLE {table_name} RENAME COLUMN box_id_new TO box_id")

        # Determinar nome da tabela Box (pode ser bau_mental_box ou supbrainnote_box)
        cursor.execute("""
            SELECT table_name
            FROM information_schema.tables
            WHERE table_name IN ('supbrainnote_box', 'bau_mental_box')
            AND table_schema = 'public'
            LIMIT 1
        """)
        box_table = cursor.fetchone()
        box_table_name = box_table[0] if box_table else 'bau_mental_box'

        # Recriar foreign key
        cursor.execute(f"""
            ALTER TABLE {table_name}
            ADD CONSTRAINT {table_name}_box_id_fk
            FOREIGN KEY (box_id)
            REFERENCES {box_table_name}(id)
            ON DELETE SET NULL
        """)
        
        # Se era supbrainnote_note, renomear para bau_mental_note
        if table_name == 'supbrainnote_note':
            cursor.execute("ALTER TABLE supbrainnote_note RENAME TO bau_mental_note")


def convert_note_id_to_uuid(apps, schema_editor):
    """Converte o campo id de Note de bigint para UUID.
    
    Se a tabela não existir ou já for UUID, não faz nada (banco novo).
    """
    db_alias = schema_editor.connection.alias

    with schema_editor.connection.cursor() as cursor:
        # Verificar se a tabela existe (pode ser bau_mental_note se banco novo)
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 FROM information_schema.tables
                WHERE table_name IN ('supbrainnote_note', 'bau_mental_note')
                AND table_schema = 'public'
            )
        """)
        table_exists = cursor.fetchone()[0]

        if not table_exists:
            # Tabela não existe ainda, não fazer nada (será criada com UUID)
            return

        # Verificar qual tabela existe e tipo do id
        cursor.execute("""
            SELECT c.table_name, c.data_type
            FROM information_schema.columns c
            JOIN information_schema.tables t ON c.table_name = t.table_name
            WHERE c.table_name IN ('supbrainnote_note', 'bau_mental_note')
            AND c.column_name = 'id'
            AND t.table_schema = 'public'
        """)
        result = cursor.fetchone()

        if not result:
            return

        table_name, data_type = result

        if data_type == 'uuid':
            # Já é UUID, não fazer nada
            return

        # Se a tabela é bau_mental_note, não fazer nada (já foi criada com UUID)
        if table_name == 'bau_mental_note':
            return

        # 1. Criar nova coluna UUID temporária
        cursor.execute(f"""
            ALTER TABLE {table_name}
            ADD COLUMN id_new UUID DEFAULT gen_random_uuid()
        """)

        # 2. Remover a coluna antiga bigint (CASCADE remove dependências automaticamente)
        cursor.execute(f"ALTER TABLE {table_name} DROP COLUMN id CASCADE")

        # 3. Renomear a nova coluna para id
        cursor.execute(f"ALTER TABLE {table_name} RENAME COLUMN id_new TO id")

        # 4. Adicionar constraint de primary key
        cursor.execute(f"ALTER TABLE {table_name} ADD PRIMARY KEY (id)")
        
        # 5. Se era supbrainnote_note, renomear para bau_mental_note
        if table_name == 'supbrainnote_note':
            cursor.execute("ALTER TABLE supbrainnote_note RENAME TO bau_mental_note")
        
        # 5. Converter related_note_id em core_notification (se existir)
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 FROM information_schema.tables
                WHERE table_name = 'core_notification'
                AND table_schema = 'public'
            )
        """)
        notification_table_exists = cursor.fetchone()[0]

        if notification_table_exists:
            cursor.execute("""
                SELECT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'core_notification'
                    AND column_name = 'related_note_id'
                    AND table_schema = 'public'
                )
            """)
            related_note_id_exists = cursor.fetchone()[0]
            
            if related_note_id_exists:
                # Verificar se já é UUID
                cursor.execute("""
                    SELECT data_type
                    FROM information_schema.columns
                    WHERE table_name = 'core_notification'
                    AND column_name = 'related_note_id'
                    AND table_schema = 'public'
                """)
                result = cursor.fetchone()
                
                if result and result[0] != 'uuid':
                    # Determinar nome da tabela Note (pode ser bau_mental_note ou supbrainnote_note)
                    cursor.execute("""
                        SELECT table_name
                        FROM information_schema.tables
                        WHERE table_name IN ('supbrainnote_note', 'bau_mental_note')
                        AND table_schema = 'public'
                        LIMIT 1
                    """)
                    note_table = cursor.fetchone()
                    note_table_name = note_table[0] if note_table else 'bau_mental_note'
                    
                    # Remover foreign key constraint
                    cursor.execute("""
                        SELECT constraint_name
                        FROM information_schema.table_constraints
                        WHERE table_name = 'core_notification'
                        AND constraint_type = 'FOREIGN KEY'
                        AND constraint_name LIKE '%related_note_id%'
                    """)
                    fk_constraints = cursor.fetchall()

                    for constraint in fk_constraints:
                        constraint_name = constraint[0]
                        cursor.execute(f'ALTER TABLE core_notification DROP CONSTRAINT IF EXISTS {constraint_name}')
                    
                    # Converter related_note_id de bigint para uuid
                    cursor.execute("""
                        ALTER TABLE core_notification
                        ADD COLUMN related_note_id_new UUID
                    """)
                    cursor.execute("ALTER TABLE core_notification DROP COLUMN related_note_id")
                    cursor.execute("ALTER TABLE core_notification RENAME COLUMN related_note_id_new TO related_note_id")
                    
                    # Recriar foreign key
                    cursor.execute(f"""
                        ALTER TABLE core_notification
                        ADD CONSTRAINT core_notification_related_note_id_fk
                        FOREIGN KEY (related_note_id)
                        REFERENCES {note_table_name}(id)
                        ON DELETE SET NULL
                    """)


def reverse_convert_box_id(apps, schema_editor):
    """Reverter conversão (não suportado - conversão irreversível)."""
    pass


def reverse_convert_note_box_id(apps, schema_editor):
    """Reverter conversão (não suportado - conversão irreversível)."""
    pass


def reverse_convert_note_id(apps, schema_editor):
    """Reverter conversão (não suportado - conversão irreversível)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bau_mental', '0001_initial'),
    ]

    operations = [
        # Limpar dados existentes (são apenas dados de teste)
        migrations.RunPython(clear_existing_data, reverse_clear_data),
        # Converter Box.id de bigint para UUID usando SQL customizado
        migrations.RunPython(convert_box_id_to_uuid, reverse_convert_box_id),
        # Converter Note.box_id de bigint para UUID (precisa ser antes de converter Note.id)
        migrations.RunPython(convert_note_box_id_to_uuid, reverse_convert_note_box_id),
        # Converter Note.id de bigint para UUID usando SQL customizado
        migrations.RunPython(convert_note_id_to_uuid, reverse_convert_note_id),
        # Atualizar definição do modelo para refletir UUID
        migrations.AlterField(
            model_name='box',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
