# Generated by Django 5.2.9 on 2025-12-27 18:54

import apps.bau_mental.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bau_mental', '0002_alter_box_id_alter_note_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='audio_file',
            field=models.FileField(storage='apps.bau_mental.storage.BauMentalAudioStorage', upload_to=apps.bau_mental.models.audio_upload_path, verbose_name='Arquivo de áudio'),
        ),
    ]
