# Generated by Django 5.2.10 on 2026-01-15 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bau_mental', '0011_add_threads'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='box',
            new_name='bau_mental__workspa_1af3f2_idx',
            old_name='supbrainnot_workspa_e64862_idx',
        ),
        migrations.RenameIndex(
            model_name='boxshare',
            new_name='bau_mental__box_id_362bb7_idx',
            old_name='supbrainnot_box_id_5e2530_idx',
        ),
        migrations.RenameIndex(
            model_name='boxshare',
            new_name='bau_mental__shared__c8f9f1_idx',
            old_name='supbrainnot_shared__c84b1c_idx',
        ),
        migrations.RenameIndex(
            model_name='boxshareinvite',
            new_name='bau_mental__email_d1a7c4_idx',
            old_name='supbrainnot_email_fd1704_idx',
        ),
        migrations.RenameIndex(
            model_name='boxshareinvite',
            new_name='bau_mental__expires_ea8edd_idx',
            old_name='supbrainnot_expires_60135e_idx',
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='bau_mental__workspa_f486ac_idx',
            old_name='supbrainnot_workspa_a9ae4d_idx',
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='bau_mental__workspa_a677cd_idx',
            old_name='supbrainnot_workspa_0d054b_idx',
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='bau_mental__workspa_52a1b9_idx',
            old_name='supbrainnot_workspa_61869d_idx',
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='bau_mental__created_372e00_idx',
            old_name='supbrainnot_created_d1321a_idx',
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='bau_mental__last_ed_aa0054_idx',
            old_name='supbrainnot_last_ed_359919_idx',
        ),
        migrations.RenameIndex(
            model_name='thread',
            new_name='bau_mental__workspa_d3eebe_idx',
            old_name='bau_mental_thread_workspace_box_idx',
        ),
        migrations.RenameIndex(
            model_name='thread',
            new_name='bau_mental__workspa_c77e1d_idx',
            old_name='bau_mental_thread_workspace_global_idx',
        ),
        migrations.RenameIndex(
            model_name='thread',
            new_name='bau_mental__created_d11b2b_idx',
            old_name='bau_mental_thread_created_by_idx',
        ),
        migrations.RenameIndex(
            model_name='threadmessage',
            new_name='bau_mental__thread__4bb048_idx',
            old_name='bau_mental_threadmessage_thread_idx',
        ),
        migrations.RenameIndex(
            model_name='threadmessage',
            new_name='bau_mental__workspa_baedd3_idx',
            old_name='bau_mental_threadmessage_workspace_idx',
        ),
        migrations.AlterField(
            model_name='thread',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em'),
        ),
        migrations.AlterField(
            model_name='threadmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em'),
        ),
        migrations.AlterField(
            model_name='threadmessage',
            name='notes_referenced',
            field=models.ManyToManyField(blank=True, help_text='Notas citadas nesta mensagem', related_name='referenced_in_messages', to='bau_mental.note', verbose_name='Notas referenciadas'),
        ),
    ]
