# Generated by Django 5.2.9 on 2025-12-25 04:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationLog',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('level', models.CharField(choices=[('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, max_length=10, verbose_name='Nível')),
                ('source', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend')], db_index=True, max_length=20, verbose_name='Origem')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('error_type', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Tipo de Erro')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL')),
                ('stack_trace', models.TextField(blank=True, null=True, verbose_name='Stack Trace')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Dados Extras')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ID da Sessão')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.workspace', verbose_name='Workspace')),
            ],
            options={
                'verbose_name': 'Log de Aplicação',
                'verbose_name_plural': 'Logs de Aplicação',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'level', 'created_at'], name='core_applic_workspa_2978e8_idx'), models.Index(fields=['workspace', 'source', 'created_at'], name='core_applic_workspa_47efe2_idx'), models.Index(fields=['created_at'], name='core_applic_created_20ec3e_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Criação'), ('update', 'Atualização'), ('delete', 'Exclusão'), ('view', 'Visualização')], max_length=20, verbose_name='Ação')),
                ('model_name', models.CharField(max_length=255, verbose_name='Model')),
                ('object_id', models.CharField(max_length=255, verbose_name='ID do Objeto')),
                ('field_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Campo')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Valor Antigo')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='Valor Novo')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data/Hora')),
                ('is_personal_data', models.BooleanField(db_index=True, default=False, verbose_name='Dados Pessoais')),
                ('data_subject', models.CharField(blank=True, help_text='Email ou identificador do titular dos dados', max_length=255, null=True, verbose_name='Titular dos Dados')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounts.workspace', verbose_name='Workspace')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'created_at'], name='core_auditl_workspa_d7ea53_idx'), models.Index(fields=['workspace', 'is_personal_data', 'created_at'], name='core_auditl_workspa_36affb_idx'), models.Index(fields=['model_name', 'object_id'], name='core_auditl_model_n_3fb686_idx'), models.Index(fields=['data_subject', 'created_at'], name='core_auditl_data_su_dc3dfc_idx')],
            },
        ),
    ]
