# Generated by Django 5.2.9 on 2026-01-07 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_notifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notificação', 'verbose_name_plural': 'Notificações'},
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='core_notifi_user_id_dd1b42_idx',
            old_name='core_notifi_user_re_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='core_notifi_user_id_dc77c0_idx',
            old_name='core_notifi_user_ty_idx',
        ),
    ]
