# Generated by Django 5.2.9 on 2025-12-25 04:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('legal_name', models.CharField(blank=True, help_text='Nome completo/razão social da empresa', max_length=255, null=True, verbose_name='Razão Social')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Endereço Completo')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado (UF)')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail de Contato')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Site')),
                ('dpo_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do DPO')),
                ('dpo_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail do DPO')),
                ('dpo_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do DPO')),
                ('dpo_address', models.TextField(blank=True, null=True, verbose_name='Endereço do DPO')),
                ('support_hours', models.CharField(blank=True, max_length=100, null=True, verbose_name='Horário de Atendimento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Workspace',
                'verbose_name_plural': 'Workspaces',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(blank=True, help_text='Opcional. 150 caracteres ou menos. Letras, dígitos e @/./+/-/_ apenas.', max_length=150, null=True, verbose_name='username')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.workspace', verbose_name='Workspace')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('terms', 'Termos e Condições'), ('privacy', 'Política de Privacidade')], max_length=20, verbose_name='Tipo de Documento')),
                ('content', models.TextField(help_text='Template com variáveis [VARIAVEL] ou {{variavel}} que serão substituídas por valores do SaaS.', verbose_name='Conteúdo')),
                ('version', models.IntegerField(default=1, verbose_name='Versão')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Documento Legal',
                'verbose_name_plural': 'Documentos Legais',
                'ordering': ['-version', '-created_at'],
                'indexes': [models.Index(fields=['document_type', 'is_active'], name='accounts_le_documen_25a1f0_idx')],
                'unique_together': {('document_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='LegalDocumentAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Aceito em')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, max_length=500, null=True, verbose_name='User Agent')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to='accounts.legaldocument', verbose_name='Documento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_acceptances', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('workspace', models.ForeignKey(blank=True, help_text='Workspace do usuário (pode ser None se usuário não tiver workspace ou documento for global).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_acceptances', to='accounts.workspace', verbose_name='Workspace')),
            ],
            options={
                'verbose_name': 'Aceitação de Documento Legal',
                'verbose_name_plural': 'Aceitações de Documentos Legais',
                'ordering': ['-accepted_at'],
                'indexes': [models.Index(fields=['user', 'accepted_at'], name='accounts_le_user_id_4c687b_idx'), models.Index(fields=['workspace', 'accepted_at'], name='accounts_le_workspa_a0ecab_idx'), models.Index(fields=['document', 'accepted_at'], name='accounts_le_documen_00071e_idx')],
                'unique_together': {('user', 'document')},
            },
        ),
    ]
