# Generated by Django 5.2.9 on 2025-12-25 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_password_reset_token'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='accounts_pa_token_e975e5_idx',
            old_name='accounts_p_token_used_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='accounts_pa_user_id_38eca7_idx',
            old_name='accounts_p_user_id_used_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='accounts_pa_expires_01b447_idx',
            old_name='accounts_p_expires_idx',
        ),
        migrations.AlterField(
            model_name='role',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.workspace', verbose_name='Workspace'),
        ),
    ]
