# Generated by Django 5.2.9 on 2025-12-25 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('client_workspace', models.CharField(blank=True, max_length=255, null=True, verbose_name='Workspace do Cliente')),
                ('status', models.CharField(choices=[('new', 'Novo'), ('contacted', 'Contactado'), ('qualified', 'Qualificado'), ('converted', 'Convertido'), ('lost', 'Perdido')], default='new', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='Origem')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.workspace', verbose_name='Workspace')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'status'], name='leads_lead_workspa_6e0a93_idx'), models.Index(fields=['workspace', 'created_at'], name='leads_lead_workspa_bcabd1_idx')],
            },
        ),
    ]
