# Generated by Django 5.2.9 on 2025-12-27 18:41

import uuid
from django.db import migrations, models


def clear_existing_data(apps, schema_editor):
    """Limpa dados existentes antes de alterar primary key para UUID.

    Nota: Esta migration limpa todos os dados existentes de Box e Note
    porque não é possível converter primary keys numéricas para UUID
    sem perder referências. Como são dados de teste, isso é aceitável.
    """
    Box = apps.get_model('supbrainnote', 'Box')
    Note = apps.get_model('supbrainnote', 'Note')

    # Deletar todas as notas primeiro (devido à foreign key)
    Note.objects.all().delete()
    # Deletar todas as caixinhas
    Box.objects.all().delete()


def reverse_clear_data(apps, schema_editor):
    """Reverter limpeza (não suportado - dados foram deletados)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('supbrainnote', '0001_initial'),
    ]

    operations = [
        # Limpar dados existentes (são apenas dados de teste)
        migrations.RunPython(clear_existing_data, reverse_clear_data),
        # Alterar campo id para UUID
        migrations.AlterField(
            model_name='box',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
