# Generated by Django 5.2.9 on 2025-12-27 18:41
# Modificado para suportar conversão de bigint para UUID em produção

import uuid
from django.db import migrations, models


def clear_existing_data(apps, schema_editor):
    """Limpa dados existentes antes de alterar primary key para UUID.

    Nota: Esta migration limpa todos os dados existentes de Box e Note
    porque não é possível converter primary keys numéricas para UUID
    sem perder referências. Como são dados de teste, isso é aceitável.
    """
    Box = apps.get_model('supbrainnote', 'Box')
    Note = apps.get_model('supbrainnote', 'Note')

    # Deletar todas as notas primeiro (devido à foreign key)
    Note.objects.all().delete()
    # Deletar todas as caixinhas
    Box.objects.all().delete()


def reverse_clear_data(apps, schema_editor):
    """Reverter limpeza (não suportado - dados foram deletados)."""
    pass


def convert_box_id_to_uuid(apps, schema_editor):
    """Converte o campo id de Box de bigint para UUID."""
    db_alias = schema_editor.connection.alias

    with schema_editor.connection.cursor() as cursor:
        # Verificar se a tabela existe
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 FROM information_schema.tables
                WHERE table_name = 'supbrainnote_box'
            )
        """)
        table_exists = cursor.fetchone()[0]

        if not table_exists:
            # Tabela não existe ainda, não fazer nada
            return

        # Verificar se a coluna já é UUID (para evitar erro em re-execução)
        cursor.execute("""
            SELECT data_type
            FROM information_schema.columns
            WHERE table_name = 'supbrainnote_box'
            AND column_name = 'id'
        """)
        result = cursor.fetchone()

        if result and result[0] == 'uuid':
            # Já está convertido, não fazer nada
            return

        # 1. Remover foreign key constraint de note.box_id (se existir e se a tabela note existir)
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 FROM information_schema.tables
                WHERE table_name = 'supbrainnote_note'
            )
        """)
        note_table_exists = cursor.fetchone()[0]

        if note_table_exists:
            cursor.execute("""
                SELECT constraint_name
                FROM information_schema.table_constraints
                WHERE table_name = 'supbrainnote_note'
                AND constraint_type = 'FOREIGN KEY'
                AND constraint_name LIKE '%box_id%'
            """)
            fk_constraints = cursor.fetchall()

            for constraint in fk_constraints:
                constraint_name = constraint[0]
                cursor.execute(f'ALTER TABLE supbrainnote_note DROP CONSTRAINT IF EXISTS {constraint_name}')

        # 2. Criar nova coluna UUID temporária
        cursor.execute("""
            ALTER TABLE supbrainnote_box
            ADD COLUMN id_new UUID DEFAULT gen_random_uuid()
        """)

        # 3. Remover a coluna antiga bigint (CASCADE remove dependências automaticamente)
        cursor.execute("ALTER TABLE supbrainnote_box DROP COLUMN id CASCADE")

        # 4. Renomear a nova coluna para id
        cursor.execute("ALTER TABLE supbrainnote_box RENAME COLUMN id_new TO id")

        # 5. Adicionar constraint de primary key
        cursor.execute("ALTER TABLE supbrainnote_box ADD PRIMARY KEY (id)")


def convert_note_id_to_uuid(apps, schema_editor):
    """Converte o campo id de Note de bigint para UUID."""
    db_alias = schema_editor.connection.alias

    with schema_editor.connection.cursor() as cursor:
        # Verificar se a tabela existe
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 FROM information_schema.tables
                WHERE table_name = 'supbrainnote_note'
            )
        """)
        table_exists = cursor.fetchone()[0]

        if not table_exists:
            # Tabela não existe ainda, não fazer nada
            return

        # Verificar se a coluna já é UUID (para evitar erro em re-execução)
        cursor.execute("""
            SELECT data_type
            FROM information_schema.columns
            WHERE table_name = 'supbrainnote_note'
            AND column_name = 'id'
        """)
        result = cursor.fetchone()

        if result and result[0] == 'uuid':
            # Já está convertido, não fazer nada
            return

        # 1. Criar nova coluna UUID temporária
        cursor.execute("""
            ALTER TABLE supbrainnote_note
            ADD COLUMN id_new UUID DEFAULT gen_random_uuid()
        """)

        # 2. Remover a coluna antiga bigint (CASCADE remove dependências automaticamente)
        cursor.execute("ALTER TABLE supbrainnote_note DROP COLUMN id CASCADE")

        # 3. Renomear a nova coluna para id
        cursor.execute("ALTER TABLE supbrainnote_note RENAME COLUMN id_new TO id")

        # 4. Adicionar constraint de primary key
        cursor.execute("ALTER TABLE supbrainnote_note ADD PRIMARY KEY (id)")

        # 5. Recriar foreign key para box_id (se a tabela box existir e já tiver sido convertida)
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 FROM information_schema.tables
                WHERE table_name = 'supbrainnote_box'
            )
        """)
        box_exists = cursor.fetchone()[0]

        if box_exists:
            # Verificar se box.id já é UUID
            cursor.execute("""
                SELECT data_type
                FROM information_schema.columns
                WHERE table_name = 'supbrainnote_box'
                AND column_name = 'id'
            """)
            box_id_type = cursor.fetchone()

            if box_id_type and box_id_type[0] == 'uuid':
                # Verificar se a coluna box_id existe
                cursor.execute("""
                    SELECT EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'supbrainnote_note'
                        AND column_name = 'box_id'
                    )
                """)
                box_id_exists = cursor.fetchone()[0]

                if box_id_exists:
                    # Verificar se já existe constraint (para evitar erro em re-execução)
                    cursor.execute("""
                        SELECT EXISTS (
                            SELECT 1 FROM information_schema.table_constraints
                            WHERE table_name = 'supbrainnote_note'
                            AND constraint_type = 'FOREIGN KEY'
                            AND constraint_name LIKE '%box_id%'
                        )
                    """)
                    fk_exists = cursor.fetchone()[0]

                    if not fk_exists:
                        # Recriar foreign key
                        cursor.execute("""
                            ALTER TABLE supbrainnote_note
                            ADD CONSTRAINT supbrainnote_note_box_id_fk
                            FOREIGN KEY (box_id)
                            REFERENCES supbrainnote_box(id)
                            ON DELETE SET NULL
                        """)


def reverse_convert_box_id(apps, schema_editor):
    """Reverter conversão (não suportado - conversão irreversível)."""
    pass


def reverse_convert_note_id(apps, schema_editor):
    """Reverter conversão (não suportado - conversão irreversível)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('supbrainnote', '0001_initial'),
    ]

    operations = [
        # Limpar dados existentes (são apenas dados de teste)
        migrations.RunPython(clear_existing_data, reverse_clear_data),
        # Converter Box.id de bigint para UUID usando SQL customizado
        migrations.RunPython(convert_box_id_to_uuid, reverse_convert_box_id),
        # Converter Note.id de bigint para UUID usando SQL customizado
        migrations.RunPython(convert_note_id_to_uuid, reverse_convert_note_id),
        # Atualizar definição do modelo para refletir UUID
        migrations.AlterField(
            model_name='box',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
