# Generated by Django 5.2.9 on 2025-12-27 19:02

import apps.supbrainnote.models
import apps.supbrainnote.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supbrainnote', '0003_alter_note_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='audio_file',
            field=models.FileField(storage=apps.supbrainnote.storage.SupBrainNoteAudioStorage(), upload_to=apps.supbrainnote.models.audio_upload_path, verbose_name='Arquivo de áudio'),
        ),
    ]
