# Generated by Django 5.2.9 on 2025-12-28 04:54

from django.contrib.postgres.indexes import GinIndex
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supbrainnote', '0005_add_fulltext_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='source_type',
            field=models.CharField(choices=[('memo', 'Memo próprio'), ('group_audio', 'Áudio de grupo'), ('forwarded', 'Áudio encaminhado')], default='memo', max_length=20, verbose_name='Tipo de origem'),
        ),
        # Re-adicionar índice que foi removido incorretamente
        migrations.AddIndex(
            model_name='note',
            index=GinIndex(
                fields=['transcript'],
                name='note_transcript_gin_idx',
                opclasses=['gin_trgm_ops'],
            ),
        ),
    ]
