# Generated by Django 5.2.9 on 2025-12-28 04:54

from django.contrib.postgres.indexes import GinIndex
from django.db import migrations, models, connection


def ensure_index_exists(apps, schema_editor):
    """Garante que o índice existe, criando apenas se não existir."""
    if connection.vendor != 'postgresql':
        return

    with connection.cursor() as cursor:
        # Verificar se índice já existe
        cursor.execute(
            """
            SELECT 1 FROM pg_indexes 
            WHERE indexname = 'note_transcript_gin_idx'
            """
        )
        if not cursor.fetchone():
            # Criar índice apenas se não existir
            # Usar IF NOT EXISTS para evitar erro se já existir
            try:
                cursor.execute(
                    """
                    CREATE INDEX IF NOT EXISTS note_transcript_gin_idx 
                    ON supbrainnote_note 
                    USING gin (transcript gin_trgm_ops)
                    """
                )
            except Exception as e:
                # Se falhar, logar mas não quebrar a migration
                # (pode ser que o índice já exista com outro nome ou formato)
                import logging
                logger = logging.getLogger(__name__)
                logger.warning(f"Erro ao criar índice note_transcript_gin_idx: {e}. Continuando...")


def reverse_ensure_index_exists(apps, schema_editor):
    """Reverte criação do índice (opcional)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('supbrainnote', '0005_add_fulltext_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='source_type',
            field=models.CharField(choices=[('memo', 'Memo próprio'), ('group_audio', 'Áudio de grupo'), ('forwarded', 'Áudio encaminhado')], default='memo', max_length=20, verbose_name='Tipo de origem'),
        ),
        # Garantir que o índice existe (criar apenas se não existir)
        # Isso resolve o problema de "relation already exists" em produção
        migrations.RunPython(
            ensure_index_exists,
            reverse_ensure_index_exists,
        ),
    ]
