# Generated by Django 5.2.9 on 2026-01-07 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supbrainnote', '0008_add_box_sharing'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='note',
            name='note_transcript_gin_idx',
        ),
        migrations.RenameIndex(
            model_name='boxshare',
            new_name='supbrainnot_box_id_5e2530_idx',
            old_name='supbrainnot_box_shar_idx',
        ),
        migrations.RenameIndex(
            model_name='boxshare',
            new_name='supbrainnot_shared__c84b1c_idx',
            old_name='supbrainnot_shared__idx',
        ),
        migrations.RenameIndex(
            model_name='boxshareinvite',
            new_name='supbrainnot_email_fd1704_idx',
            old_name='supbrainnot_email_to_idx',
        ),
        migrations.RenameIndex(
            model_name='boxshareinvite',
            new_name='supbrainnot_expires_60135e_idx',
            old_name='supbrainnot_expires_idx',
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='supbrainnot_created_d1321a_idx',
            old_name='supbrainnot_created_idx',
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='supbrainnot_last_ed_359919_idx',
            old_name='supbrainnot_last_edi_idx',
        ),
    ]
