# Generated by Django 5.2.9 on 2025-12-26 03:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_add_updated_at_to_password_reset_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('portfolio_type', models.CharField(choices=[('acoes_br', 'Ações Brasileiras')], default='acoes_br', max_length=20, verbose_name='Tipo de Carteira')),
                ('name', models.CharField(blank=True, help_text='Nome opcional para identificar a carteira', max_length=255, null=True, verbose_name='Nome')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.workspace', verbose_name='Workspace')),
            ],
            options={
                'verbose_name': 'Carteira',
                'verbose_name_plural': 'Carteiras',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ticker', models.CharField(help_text='Código do ativo (ex: TAEE11, PETR4)', max_length=20, verbose_name='Ticker')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Quantidade')),
                ('average_price', models.DecimalField(decimal_places=2, help_text='Preço médio de compra do ativo', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço Médio')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.workspace', verbose_name='Workspace')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='investments.portfolio', verbose_name='Carteira')),
            ],
            options={
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('raw_text', models.TextField(help_text='Descreva como você gosta de investir', verbose_name='Estratégia (Texto Livre)')),
                ('parsed_rules', models.JSONField(blank=True, default=dict, help_text='Regras parseadas do texto (preenchido automaticamente)', verbose_name='Regras Estruturadas')),
                ('strategy_type', models.CharField(blank=True, choices=[('dividendos', 'Dividendos'), ('value', 'Value Investing'), ('growth', 'Growth'), ('hibrida', 'Híbrida')], help_text='Identificado automaticamente pelo parser', max_length=20, null=True, verbose_name='Tipo de Estratégia')),
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strategy', to='investments.portfolio', verbose_name='Carteira')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.workspace', verbose_name='Workspace')),
            ],
            options={
                'verbose_name': 'Estratégia',
                'verbose_name_plural': 'Estratégias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['workspace', 'portfolio_type'], name='investments_workspa_0607d5_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['workspace', 'created_at'], name='investments_workspa_b29e56_idx'),
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'portfolio_type'), name='unique_active_portfolio_per_type'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['portfolio', 'ticker'], name='investments_portfol_a4efea_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['workspace', 'ticker'], name='investments_workspa_7f5123_idx'),
        ),
        migrations.AddIndex(
            model_name='strategy',
            index=models.Index(fields=['workspace', 'strategy_type'], name='investments_workspa_ef5506_idx'),
        ),
    ]
