# Generated by Django 5.2.9 on 2025-12-26 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_updated_at_to_password_reset_token'),
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': 'Ativo', 'verbose_name_plural': 'Ativos'},
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('portfolio', 'ticker')},
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('total_value', models.DecimalField(decimal_places=2, help_text='Valor total da carteira no momento do snapshot', max_digits=15, verbose_name='Valor Total')),
                ('assets_data', models.JSONField(default=dict, help_text='Snapshot dos ativos no momento (ticker, quantidade, preço)', verbose_name='Dados dos Ativos')),
                ('notes', models.TextField(blank=True, help_text='Notas opcionais sobre o snapshot', null=True, verbose_name='Observações')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='investments.portfolio', verbose_name='Carteira')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.workspace', verbose_name='Workspace')),
            ],
            options={
                'verbose_name': 'Snapshot de Carteira',
                'verbose_name_plural': 'Snapshots de Carteira',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['portfolio', 'created_at'], name='investments_portfol_fac8ba_idx'), models.Index(fields=['workspace', 'created_at'], name='investments_workspa_c4079f_idx')],
            },
        ),
    ]
