# Generated by Django 5.2.9 on 2025-12-26 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_alter_asset_options_alter_asset_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='portfolio',
            name='unique_active_portfolio_per_type',
        ),
    ]
