# Generated by Django 5.2.9 on 2025-12-26 05:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_updated_at_to_password_reset_token'),
        ('investments', '0003_remove_unique_portfolio_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='DividendHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ticker', models.CharField(db_index=True, help_text='Código do ativo (ex: TAEE11, PETR4)', max_length=20, verbose_name='Ticker')),
                ('dividends_data', models.JSONField(default=list, help_text='Lista de dividendos pagos (últimos 12 meses)', verbose_name='Dados de Dividendos')),
                ('total_last_12_months', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Soma dos dividendos dos últimos 12 meses', max_digits=15, verbose_name='Total Últimos 12 Meses')),
                ('average_monthly', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Média mensal de dividendos', max_digits=15, verbose_name='Média Mensal')),
                ('regularity_score', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Score de 0-1 indicando regularidade dos pagamentos', max_digits=5, verbose_name='Score de Regularidade')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Data da última atualização dos dados', verbose_name='Última Atualização')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.workspace', verbose_name='Workspace')),
            ],
            options={
                'verbose_name': 'Histórico de Dividendos',
                'verbose_name_plural': 'Históricos de Dividendos',
                'indexes': [models.Index(fields=['ticker', 'last_updated'], name='investments_ticker_a345e3_idx'), models.Index(fields=['workspace', 'ticker'], name='investments_workspa_8ede0f_idx')],
                'unique_together': {('workspace', 'ticker')},
            },
        ),
    ]
