# Generated by Django 5.2.9 on 2025-12-26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_updated_at_to_password_reset_token'),
        ('investments', '0004_dividendhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ticker', models.CharField(help_text='Código do ativo (ex: TAEE11, PETR4)', max_length=20, verbose_name='Ticker')),
                ('transaction_type', models.CharField(choices=[('buy', 'Compra'), ('sell', 'Venda')], max_length=4, verbose_name='Tipo de Transação')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço Unitário', help_text='Preço da transação')),
                ('market_price', models.DecimalField(blank=True, decimal_places=2, help_text='Preço de mercado no momento da transação', max_digits=15, null=True, verbose_name='Preço de Mercado')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='quantity * unit_price', max_digits=15, verbose_name='Valor Total')),
                ('transaction_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Corretagem, taxas, etc.', max_digits=15, verbose_name='Custo da Transação')),
                ('recommendation_id', models.CharField(blank=True, help_text='ID da recomendação que gerou esta transação (se aplicável)', max_length=255, null=True, verbose_name='ID da Recomendação')),
                ('notes', models.TextField(blank=True, help_text='Motivo, contexto, notas sobre a transação', null=True, verbose_name='Observações')),
                ('new_average_price', models.DecimalField(blank=True, decimal_places=2, help_text='Preço médio após esta transação', max_digits=15, null=True, verbose_name='Novo Preço Médio')),
                ('new_quantity', models.DecimalField(blank=True, decimal_places=4, help_text='Quantidade após esta transação', max_digits=15, null=True, verbose_name='Nova Quantidade')),
                ('asset', models.ForeignKey(blank=True, help_text='Null se foi venda total (ativo deletado)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='investments.asset', verbose_name='Ativo')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='investments.portfolio', verbose_name='Carteira')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.workspace', verbose_name='Workspace')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['portfolio', 'created_at'], name='investments_portfolio_created_idx'),
                    models.Index(fields=['portfolio', 'ticker'], name='investments_portfolio_ticker_idx'),
                    models.Index(fields=['ticker', 'transaction_type'], name='investments_ticker_type_idx'),
                    models.Index(fields=['recommendation_id'], name='investments_recommendation_idx'),
                    models.Index(fields=['workspace', 'created_at'], name='investments_workspace_created_idx'),
                ],
            },
        ),
    ]

