# Generated by Django 5.2.9 on 2025-12-26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_updated_at_to_password_reset_token'),
        ('investments', '0005_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Valor que o usuário queria investir', max_digits=15, verbose_name='Valor Solicitado')),
                ('recommendation_data', models.JSONField(default=dict, help_text='JSON completo da recomendação retornada', verbose_name='Dados da Recomendação')),
                ('was_followed', models.BooleanField(default=False, help_text='Se o usuário seguiu esta recomendação', verbose_name='Foi Seguida')),
                ('executed_data', models.JSONField(blank=True, default=dict, help_text='O que foi realmente executado (se diferente da recomendação)', null=True, verbose_name='Dados Executados')),
                ('notes', models.TextField(blank=True, help_text='Motivo de não seguir, ajustes feitos, etc.', null=True, verbose_name='Observações')),
                ('market_context', models.JSONField(blank=True, default=dict, help_text='IBOV, volatilidade, dados fundamentalistas no momento', verbose_name='Contexto de Mercado')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='investments.portfolio', verbose_name='Carteira')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.workspace', verbose_name='Workspace')),
            ],
            options={
                'verbose_name': 'Recomendação',
                'verbose_name_plural': 'Recomendações',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['portfolio', 'created_at'], name='investments_recomm_portfolio_created_idx'),
                    models.Index(fields=['portfolio', 'was_followed'], name='investments_recomm_portfolio_followed_idx'),
                    models.Index(fields=['workspace', 'created_at'], name='investments_recomm_workspace_created_idx'),
                ],
            },
        ),
    ]



