# Generated by Django 5.2.9 on 2025-12-26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_updated_at_to_password_reset_token'),
        ('investments', '0006_recommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DividendReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ticker', models.CharField(max_length=20, verbose_name='Ticker')),
                ('payment_date', models.DateField(help_text='Data em que o dividendo foi creditado', verbose_name='Data de Pagamento')),
                ('base_date', models.DateField(blank=True, help_text='Data base do dividendo', null=True, verbose_name='Data Base')),
                ('quantity_owned', models.DecimalField(decimal_places=4, help_text='Quantidade de ações possuídas na data base', max_digits=15, verbose_name='Quantidade Possuída')),
                ('dividend_per_share', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Dividendo por Ação')),
                ('total_gross', models.DecimalField(decimal_places=2, help_text='quantity_owned * dividend_per_share', max_digits=15, verbose_name='Total Bruto')),
                ('tax_withheld', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='IR retido na fonte', max_digits=15, verbose_name='Imposto Retido')),
                ('total_net', models.DecimalField(decimal_places=2, help_text='total_gross - tax_withheld', max_digits=15, verbose_name='Total Líquido')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dividends_received', to='investments.asset', verbose_name='Ativo')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends_received', to='investments.portfolio', verbose_name='Carteira')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.workspace', verbose_name='Workspace')),
            ],
            options={
                'verbose_name': 'Dividendo Recebido',
                'verbose_name_plural': 'Dividendos Recebidos',
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [
                    models.Index(fields=['portfolio', 'payment_date'], name='investments_dividend_portfolio_payment_idx'),
                    models.Index(fields=['ticker', 'payment_date'], name='investments_dividend_ticker_payment_idx'),
                    models.Index(fields=['workspace', 'payment_date'], name='investments_dividend_workspace_payment_idx'),
                ],
            },
        ),
    ]



