# Generated by Django 5.2.9 on 2025-12-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_updated_at_to_password_reset_token'),
        ('investments', '0007_dividendreceived'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ticker', models.CharField(db_index=True, max_length=20, verbose_name='Ticker')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Preço')),
                ('change_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Variação Percentual')),
                ('volume', models.BigIntegerField(blank=True, null=True, verbose_name='Volume')),
                ('market_cap', models.BigIntegerField(blank=True, null=True, verbose_name='Market Cap')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.workspace', verbose_name='Workspace')),
            ],
            options={
                'verbose_name': 'Histórico de Preço',
                'verbose_name_plural': 'Históricos de Preços',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['ticker', 'created_at'], name='investments_price_ticker_created_idx'),
                    models.Index(fields=['workspace', 'ticker', 'created_at'], name='investments_price_workspace_ticker_idx'),
                ],
            },
        ),
    ]

