# Generated by Django 5.2.9 on 2025-12-26

from django.db import migrations


def migrate_existing_assets(apps, schema_editor):
    """Cria transações iniciais para ativos existentes."""
    Asset = apps.get_model("investments", "Asset")
    Transaction = apps.get_model("investments", "Transaction")

    for asset in Asset.objects.all():
        Transaction.objects.create(
            workspace=asset.workspace,
            portfolio=asset.portfolio,
            asset=asset,
            ticker=asset.ticker,
            transaction_type="buy",
            quantity=asset.quantity,
            unit_price=asset.average_price,
            total_amount=asset.quantity * asset.average_price,
            new_average_price=asset.average_price,
            new_quantity=asset.quantity,
            notes="Migração de dados existentes",
        )


def reverse_migrate_existing_assets(apps, schema_editor):
    """Remove transações de migração."""
    Transaction = apps.get_model("investments", "Transaction")
    Transaction.objects.filter(notes="Migração de dados existentes").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0008_marketpricehistory'),
    ]

    operations = [
        migrations.RunPython(migrate_existing_assets, reverse_migrate_existing_assets),
    ]

