# Generated by Django 5.2.9 on 2025-12-26 20:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_updated_at_to_password_reset_token'),
        ('investments', '0011_remove_old_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFreshness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('data_type', models.CharField(choices=[('quote', 'Cotação'), ('fundamental', 'Fundamentalista'), ('dividend_history', 'Histórico de Dividendos'), ('market_context', 'Contexto de Mercado')], max_length=50, verbose_name='Tipo de Dado')),
                ('ticker', models.CharField(blank=True, help_text='Null se for dados gerais (ex: IBOV, Selic)', max_length=20, null=True, verbose_name='Ticker')),
                ('last_updated', models.DateTimeField(verbose_name='Última Atualização')),
                ('next_update_due', models.DateTimeField(verbose_name='Próxima Atualização Devida')),
                ('is_fresh', models.BooleanField(default=True, verbose_name='Está Atualizado')),
                ('freshness_score', models.DecimalField(decimal_places=2, default=Decimal('1.0'), help_text='1.0 = totalmente atualizado, 0.0 = desatualizado', max_digits=5, verbose_name='Score de Atualização')),
                ('update_frequency_minutes', models.IntegerField(default=5, verbose_name='Frequência de Atualização (minutos)')),
            ],
            options={
                'verbose_name': 'Controle de Atualização',
                'verbose_name_plural': 'Controles de Atualização',
            },
        ),
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('risk_tolerance', models.CharField(choices=[('conservador', 'Conservador'), ('moderado', 'Moderado'), ('arrojado', 'Arrojado')], max_length=20, verbose_name='Tolerância a Risco')),
                ('investment_horizon', models.CharField(choices=[('curto', 'Curto Prazo'), ('medio', 'Médio Prazo'), ('longo', 'Longo Prazo')], max_length=20, verbose_name='Horizonte de Investimento')),
                ('primary_goal', models.CharField(choices=[('renda_passiva', 'Renda Passiva'), ('crescimento', 'Crescimento'), ('preservacao', 'Preservação')], max_length=50, verbose_name='Objetivo Principal')),
                ('experience_level', models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], default='iniciante', max_length=20, verbose_name='Nível de Experiência')),
                ('total_invested', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Total Investido')),
                ('average_dividend_yield', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='DY Médio')),
                ('diversification_score', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='0-1 (quanto mais diversificado, maior)', max_digits=5, verbose_name='Score de Diversificação')),
                ('concentration_risk', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='0-1 (quanto mais concentrado, maior risco)', max_digits=5, verbose_name='Risco de Concentração')),
                ('adherence_to_recommendations', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='% de recomendações seguidas (0-1)', max_digits=5, verbose_name='Aderência a Recomendações')),
                ('average_holding_period', models.IntegerField(default=0, help_text='Dias médios de retenção', verbose_name='Período Médio de Retenção')),
                ('last_analyzed', models.DateTimeField(auto_now=True, verbose_name='Última Análise')),
                ('confidence_score', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Confiança na inferência (0-1)', max_digits=5, verbose_name='Score de Confiança')),
                ('analysis_data', models.JSONField(default=dict, help_text='Histórico de análises, padrões identificados, etc.', verbose_name='Dados de Análise')),
            ],
            options={
                'verbose_name': 'Perfil do Investidor',
                'verbose_name_plural': 'Perfis de Investidores',
            },
        ),
        migrations.CreateModel(
            name='PortfolioChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('is_from_user', models.BooleanField(default=True, help_text='Se a mensagem é do usuário ou da IA', verbose_name='Do Usuário')),
                ('context_snapshot', models.JSONField(default=dict, help_text='Snapshot do contexto no momento da mensagem', verbose_name='Snapshot do Contexto')),
                ('ai_response', models.TextField(blank=True, verbose_name='Resposta da IA')),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=2, help_text='Confiança da resposta (0-1)', max_digits=5, null=True, verbose_name='Confiança da IA')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
            ],
            options={
                'verbose_name': 'Mensagem do Chat',
                'verbose_name_plural': 'Mensagens do Chat',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SectorMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ticker', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Ticker')),
                ('sector', models.CharField(help_text="Setor da empresa (ex: 'financeiro', 'energia', 'utilities')", max_length=100, verbose_name='Setor')),
                ('subsector', models.CharField(blank=True, help_text="Subsetor opcional (ex: 'bancos', 'seguros', 'transmissão')", max_length=100, null=True, verbose_name='Subsetor')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Empresa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Mapeamento de Setor',
                'verbose_name_plural': 'Mapeamentos de Setores',
            },
        ),
        migrations.CreateModel(
            name='StrategyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('period_start', models.DateField(verbose_name='Início do Período')),
                ('period_end', models.DateField(verbose_name='Fim do Período')),
                ('total_return', models.DecimalField(decimal_places=2, help_text='Retorno total no período (%)', max_digits=10, verbose_name='Retorno Total')),
                ('dividend_yield_realized', models.DecimalField(decimal_places=2, help_text='DY realizado (dividendos recebidos / valor investido)', max_digits=5, verbose_name='DY Realizado')),
                ('recommendations_followed', models.IntegerField(default=0, verbose_name='Recomendações Seguidas')),
                ('recommendations_total', models.IntegerField(default=0, verbose_name='Total de Recomendações')),
                ('adherence_rate', models.DecimalField(decimal_places=2, help_text='recommendations_followed / recommendations_total', max_digits=5, verbose_name='Taxa de Aderência')),
                ('performance_score', models.DecimalField(decimal_places=2, help_text='Score calculado: (total_return * 0.4) + (dividend_yield_realized * 0.4) + (adherence_rate * 0.2) * 100', max_digits=5, verbose_name='Score de Performance')),
                ('vs_ibovespa', models.DecimalField(decimal_places=2, help_text='Diferença percentual vs IBOV', max_digits=10, verbose_name='vs IBOV')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='Calculado Em')),
            ],
            options={
                'verbose_name': 'Performance de Estratégia',
                'verbose_name_plural': 'Performances de Estratégias',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='StrategyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(help_text="Nome da estratégia (ex: 'Dividendos Defensivos')", max_length=255, verbose_name='Nome')),
                ('slug', models.SlugField(help_text='Identificador único da estratégia', unique=True, verbose_name='Slug')),
                ('description', models.TextField(help_text='Descrição detalhada da estratégia', verbose_name='Descrição')),
                ('category', models.CharField(help_text="Categoria da estratégia: 'dividendos', 'value', 'growth', 'balanced'", max_length=50, verbose_name='Categoria')),
                ('base_criteria', models.JSONField(default=dict, help_text='Critérios base da estratégia em formato JSON', verbose_name='Critérios Base')),
                ('adaptation_logic', models.TextField(help_text='Instruções para IA adaptar critérios baseado em contexto', verbose_name='Lógica de Adaptação')),
                ('performance_score', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Score de 0-5 estrelas (convertido de 0-100)', max_digits=5, verbose_name='Score de Performance')),
                ('is_active', models.BooleanField(default=True, help_text='Se a estratégia está ativa', verbose_name='Ativo')),
                ('is_system_template', models.BooleanField(default=True, help_text='Se é template do sistema ou customizado', verbose_name='Template do Sistema')),
                ('priority', models.IntegerField(default=0, help_text='Ordem de prioridade (maior = mais prioritário)', verbose_name='Prioridade')),
                ('created_by_ai', models.BooleanField(default=True, verbose_name='Criado por IA')),
                ('last_validated', models.DateTimeField(blank=True, null=True, verbose_name='Última Validação')),
                ('validation_status', models.CharField(choices=[('valid', 'Válida'), ('needs_review', 'Precisa Revisão'), ('invalid', 'Inválida'), ('pending', 'Pendente')], default='pending', max_length=20, verbose_name='Status de Validação')),
            ],
            options={
                'verbose_name': 'Template de Estratégia',
                'verbose_name_plural': 'Templates de Estratégias',
                'ordering': ['-performance_score', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='StrategyValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('validation_status', models.CharField(choices=[('valid', 'Válida'), ('needs_review', 'Precisa Revisão'), ('invalid', 'Inválida'), ('warning', 'Aviso')], max_length=20, verbose_name='Status de Validação')),
                ('validation_result', models.JSONField(default=dict, help_text='Detalhes da validação (criteria_valid, market_conditions_ok, issues, warnings)', verbose_name='Resultado da Validação')),
                ('suggested_adjustments', models.JSONField(default=dict, help_text='Ajustes sugeridos pela IA', verbose_name='Ajustes Sugeridos')),
                ('validated_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Validação')),
                ('validated_by', models.CharField(choices=[('ai', 'IA'), ('user', 'Usuário')], default='ai', max_length=50, verbose_name='Validado Por')),
            ],
            options={
                'verbose_name': 'Validação de Estratégia',
                'verbose_name_plural': 'Validações de Estratégias',
                'ordering': ['-validated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('excluded_sectors', models.JSONField(default=list, help_text='Lista de setores que o usuário não quer investir', verbose_name='Setores Excluídos')),
                ('preferred_sectors', models.JSONField(default=list, help_text='Lista de setores preferidos pelo usuário', verbose_name='Setores Preferidos')),
                ('additional_criteria', models.TextField(blank=True, help_text='Critérios adicionais em texto livre', verbose_name='Critérios Adicionais')),
                ('restrictions', models.JSONField(default=dict, help_text='Restrições específicas (ex: max_concentration_per_asset)', verbose_name='Restrições')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Preferências do Usuário',
                'verbose_name_plural': 'Preferências dos Usuários',
            },
        ),
        migrations.RenameIndex(
            model_name='dividendreceived',
            new_name='investments_portfol_72a260_idx',
            old_name='investments_dividend_portfolio_payment_idx',
        ),
        migrations.RenameIndex(
            model_name='dividendreceived',
            new_name='investments_ticker_9cbbc6_idx',
            old_name='investments_dividend_ticker_payment_idx',
        ),
        migrations.RenameIndex(
            model_name='dividendreceived',
            new_name='investments_workspa_b072b7_idx',
            old_name='investments_dividend_workspace_payment_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='investments_portfol_b47e3e_idx',
            old_name='investments_portfolio_created_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='investments_portfol_4a3bfd_idx',
            old_name='investments_portfolio_ticker_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='investments_ticker_284861_idx',
            old_name='investments_ticker_type_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='investments_recomme_560789_idx',
            old_name='investments_recommendation_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='investments_workspa_e26094_idx',
            old_name='investments_workspace_created_idx',
        ),
        migrations.AddField(
            model_name='datafreshness',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.workspace', verbose_name='Workspace'),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='portfolio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='investments.portfolio', verbose_name='Carteira'),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.workspace', verbose_name='Workspace'),
        ),
        migrations.AddField(
            model_name='portfoliochat',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='investments.portfolio', verbose_name='Carteira'),
        ),
        migrations.AddField(
            model_name='portfoliochat',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.workspace', verbose_name='Workspace'),
        ),
        migrations.AddField(
            model_name='sectormapping',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.workspace', verbose_name='Workspace'),
        ),
        migrations.AddField(
            model_name='strategyperformance',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_performances', to='investments.portfolio', verbose_name='Carteira'),
        ),
        migrations.AddField(
            model_name='strategyperformance',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.workspace', verbose_name='Workspace'),
        ),
        migrations.AddField(
            model_name='strategytemplate',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.workspace', verbose_name='Workspace'),
        ),
        migrations.AddField(
            model_name='strategyperformance',
            name='strategy_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='investments.strategytemplate', verbose_name='Template de Estratégia'),
        ),
        migrations.AddField(
            model_name='strategyvalidation',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_validations', to='investments.portfolio', verbose_name='Carteira'),
        ),
        migrations.AddField(
            model_name='strategyvalidation',
            name='strategy_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='investments.strategytemplate', verbose_name='Template de Estratégia'),
        ),
        migrations.AddField(
            model_name='strategyvalidation',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.workspace', verbose_name='Workspace'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='portfolio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='investments.portfolio', verbose_name='Carteira'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.workspace', verbose_name='Workspace'),
        ),
        migrations.AddIndex(
            model_name='datafreshness',
            index=models.Index(fields=['data_type', 'last_updated'], name='investments_data_ty_cb2e74_idx'),
        ),
        migrations.AddIndex(
            model_name='datafreshness',
            index=models.Index(fields=['is_fresh', 'next_update_due'], name='investments_is_fres_352023_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='datafreshness',
            unique_together={('workspace', 'data_type', 'ticker')},
        ),
        migrations.AddIndex(
            model_name='portfoliochat',
            index=models.Index(fields=['portfolio', 'created_at'], name='investments_portfol_cbce5d_idx'),
        ),
        migrations.AddIndex(
            model_name='sectormapping',
            index=models.Index(fields=['sector', 'is_active'], name='investments_sector_f26af0_idx'),
        ),
        migrations.AddIndex(
            model_name='sectormapping',
            index=models.Index(fields=['ticker'], name='investments_ticker_f18e54_idx'),
        ),
        migrations.AddIndex(
            model_name='strategytemplate',
            index=models.Index(fields=['category', 'is_active'], name='investments_categor_586a77_idx'),
        ),
        migrations.AddIndex(
            model_name='strategytemplate',
            index=models.Index(fields=['performance_score'], name='investments_perform_6c84e0_idx'),
        ),
        migrations.AddIndex(
            model_name='strategytemplate',
            index=models.Index(fields=['slug'], name='investments_slug_580d92_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyperformance',
            index=models.Index(fields=['strategy_template', 'period_end'], name='investments_strateg_1b8925_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyperformance',
            index=models.Index(fields=['portfolio', 'period_end'], name='investments_portfol_9b55fd_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyvalidation',
            index=models.Index(fields=['strategy_template', 'validated_at'], name='investments_strateg_1c98f3_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyvalidation',
            index=models.Index(fields=['portfolio', 'validated_at'], name='investments_portfol_6d4af2_idx'),
        ),
    ]
