# Generated by Django 5.2.9 on 2025-12-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_updated_at_to_password_reset_token'),
        ('investments', '0010_datafreshness_investorprofile_portfoliochat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategytemplate',
            name='slug',
            field=models.SlugField(help_text='Identificador único da estratégia', verbose_name='Slug'),
        ),
        migrations.AlterUniqueTogether(
            name='strategytemplate',
            unique_together={('workspace', 'slug')},
        ),
    ]
