# Generated by Django 5.2.9 on 2025-12-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_updated_at_to_password_reset_token'),
        ('investments', '0011_alter_strategytemplate_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectormapping',
            name='ticker',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Ticker'),
        ),
        migrations.AlterUniqueTogether(
            name='sectormapping',
            unique_together={('workspace', 'ticker')},
        ),
    ]
