# Generated by Django 5.2.9 on 2025-12-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0012_alter_sectormapping_ticker_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='datafreshness',
            name='investments_data_ty_cb2e74_idx',
        ),
        migrations.RemoveIndex(
            model_name='datafreshness',
            name='investments_is_fres_352023_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfoliochat',
            name='investments_portfol_cbce5d_idx',
        ),
        migrations.RemoveIndex(
            model_name='sectormapping',
            name='investments_sector_f26af0_idx',
        ),
        migrations.RemoveIndex(
            model_name='sectormapping',
            name='investments_ticker_f18e54_idx',
        ),
        migrations.RemoveIndex(
            model_name='strategyperformance',
            name='investments_strateg_1b8925_idx',
        ),
        migrations.RemoveIndex(
            model_name='strategyperformance',
            name='investments_portfol_9b55fd_idx',
        ),
        migrations.RemoveIndex(
            model_name='strategytemplate',
            name='investments_categor_586a77_idx',
        ),
        migrations.RemoveIndex(
            model_name='strategytemplate',
            name='investments_perform_6c84e0_idx',
        ),
        migrations.RemoveIndex(
            model_name='strategytemplate',
            name='investments_slug_580d92_idx',
        ),
        migrations.RemoveIndex(
            model_name='strategyvalidation',
            name='investments_strateg_1c98f3_idx',
        ),
        migrations.RemoveIndex(
            model_name='strategyvalidation',
            name='investments_portfol_6d4af2_idx',
        ),
        migrations.AlterUniqueTogether(
            name='datafreshness',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='strategytemplate',
            name='adaptation_logic',
            field=models.TextField(blank=True, help_text='Instruções para IA adaptar critérios baseado em contexto', verbose_name='Lógica de Adaptação'),
        ),
        migrations.AlterField(
            model_name='strategytemplate',
            name='slug',
            field=models.SlugField(help_text='Identificador único da estratégia', max_length=255, verbose_name='Slug'),
        ),
    ]
